version: '3.6'

services:
  server-api:
    container_name: server-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_DATABASE: test
      NODE_ENV: development
    networks:
      - nest-mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    networks:
      - nest-mysql

networks:
  nest-mysql:
